import React from 'react';
import ReactDOM from 'react-dom';
import Types from './components/Types'

ReactDOM.render(
    <div>
        <section className="page-header">
            <h1 className="project-name">Form Types Reference</h1>
            <h2 className="project-tagline">Symfony comes standard with a large group of field types that cover all of the common form fields and data types you'll encounter.</h2>

            <a href="https://github.com/phptopup/symfony-form" className="btn">View on GitHub</a>
            <a href="https://github.com/phptopup/symfony-form/zipball/master" className="btn">Download .zip</a>
            <a href="https://github.com/phptopup/symfony-form/tarball/master" className="btn">Download .tar.gz</a>
        </section>
        <section className="main-content">
            <Types />

            <footer className="site-footer">
                <span className="site-footer-owner"><a href="https://phptopup.github.io/symfony-form/index.html">This page</a> is maintained by <a href="https://github.com/yceruto">Yonel Ceruto</a>.</span>
                <span className="site-footer-credits">The content of this page was generated by <a href="https://github.com/phptopup/symfony-form">phptopup/symfony-form</a>.</span>
            </footer>
        </section>
    </div>,
    document.getElementById('root')
);
