import React from 'react';
import ReactDOM from 'react-dom';
import Type from './components/Type'

class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            error: null,
            is_loaded: false,
            version: null,
            updated_at: null,
            types: [],
            type_extensions: [],
            type_guessers: []
        };
    }

    componentDidMount() {
        fetch('data.json')
            .then(res => res.json())
            .then(
                (result) => {
                    this.setState({
                        is_loaded: true,
                        version: result.version,
                        updated_at: result.updated_at,
                        types: result.types,
                        type_extensions: result.type_extensions,
                        type_guessers: result.type_guessers
                    });
                },
                // Note: it's important to handle errors here
                // instead of a catch() block so that we don't swallow
                // exceptions from actual bugs in components.
                (error) => {
                    this.setState({
                        is_loaded: true,
                        error
                    });
                }
            )
    }

    render() {
        const {error, is_loaded, version, updated_at, types, type_extensions, type_guessers} = this.state;

        if (error) {
            return <div>Error: {error.message}</div>;
        }
        if (!is_loaded) {
            return '';
        }

        return (
            <div>
                <section className="page-header">
                    <h1 className="project-name">Form Types Reference</h1>
                    <h2 className="project-tagline">Symfony comes standard with a large group of field types that cover all of the common form fields and data types you'll encounter.</h2>

                    <a href="https://github.com/phptopup/symfony-form" className="btn">View on GitHub</a>
                    <a href="https://github.com/phptopup/symfony-form/zipball/master" className="btn">Download .zip</a>
                    <a href="https://github.com/phptopup/symfony-form/tarball/master" className="btn">Download .tar.gz</a>
                </section>
                <section className="main-content">
                    <h2 id="types">Built-in Field Types</h2>
                    <div style={{display: 'inline-block'}}>
                        {types.map(type => (
                            <a key={type.name} href={'#' + type.name} title={type.class} className="float-left mr-0-5"><code>{type.name}</code></a>
                        ))}
                    </div>

                    <h2 id="types">Type Extensions</h2>
                    <div style={{display: 'inline-block'}}>
                        {type_extensions.map(type => (
                            <a key={type.name} href={'#' + type.name} title={type.class} className="float-left mr-0-5"><code>{type.name}</code></a>
                        ))}
                    </div>

                    <h2 id="types">Type Guessers</h2>
                    <div style={{display: 'inline-block'}}>
                        {type_guessers.map(type => (
                            <a key={type.name} href={'#' + type.name} title={type.class} className="float-left mr-0-5"><code>{type.name}</code></a>
                        ))}
                    </div>

                </section>
                <section className="build-info-container">
                    <div className="build-info">
                        <div>Symfony version: <strong>{version}</strong></div>
                        <div>Last update: <strong>{updated_at}</strong></div>
                    </div>
                </section>
                <section className="main-content">
                    {types.map(type => (
                        <Type key={type.name}
                              name={type.name}
                              cls={type.class}
                              api={type.api}
                              block_prefix={type.block_prefix}
                              options={type.options}
                              parent_types={type.parent_types}
                              type_extensions={type.type_extensions}
                        />
                    ))}

                    <footer className="site-footer">
                        <span className="site-footer-owner"><a href="https://phptopup.github.io/symfony-form/index.html">This page</a> is maintained by <a href="https://github.com/yceruto">Yonel Ceruto</a>.</span>
                        <span className="site-footer-credits">The content of this page was generated by <a href="https://github.com/phptopup/symfony-form">phptopup/symfony-form</a>.</span>
                    </footer>
                </section>
            </div>
        );
    }
}

ReactDOM.render(
    <App />,
    document.getElementById('root')
);
